version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1230
      POSTGRES_DB: cockpit
      # POSTGRES_USER: rafael
      PGDATA: /var/lib/postgresql/data/pgdat
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080